### ISSUE TITLE
Transformer spike error

### ISSUE THREAD

**Issue by alirezaamir** [ucb-bar/gemmini-rocc-tests#24]
Hi, I tried to run spike on the transformer code, but I got the following error:
spike: ../gemmini/gemmini.cc:367: void gemmini_t::config(reg_t, reg_t): Assertion `false' failed.

my gemmini branch is v0.6.4, the shipyard is at 117624d8, and the gemmini-rocc-test is bert-softmax-hasan.
I could run spike successfully for other applications such as resnet50 and mobilenet, but I got the error for the transformer. 

Thanks in advance for the help.

**Comment by hngenc** [comment]
The transformer branch isn't "officially" supported yet. But if you want to use it right now, you need to use the `gemmini-bert` branch of Spike
