### ISSUE TITLE
Gemmini 8x8

### ISSUE THREAD

**Issue by mbelda** [ucb-bar/gemmini-rocc-tests#36]
Hello,

Is this prepared for any dimension of gemmini?
I was able to run it on a Rocket + 16x16 Gemmini.
But now I am trying to run it on a Rocket + 8x8 Gemmini and I am having issues.
It executes fine if I select the cpu mode, but when using the default parameters (ws and conv) it gets stucked after matmul 5.

I compiled it for linux with riscv64-unknown-linux-gcc and it is running on a debian.

**Comment by hngenc** [comment]
We've run 8x8 in the past (not recently, I think, but nothing we added recently should have broken it).

Are you sure you re-ran `./build.sh` after  generating the 8x8 Gemmini? That would change the `DIM` variable, so everything would have to be recompiled for that.

Also, which Gemmini commit and `gemmini-rocc-tests` commit are you on?

**Comment by mbelda** [comment]
It was the configuration file. 
Sorry and thanks!

**Comment by hngenc** [comment]
No worries; thanks for the update!

**Comment by ethan2339** [comment]
@mbelda Hello, may I ask which configuration needs to be changed? I have currently modified gemmini_para.h in gemmini-rocc-test/include/ to match the configuration of gemmini, but after compiling with ./build.sh, it still cannot run on an 8*8 matrix.
