### ISSUE TITLE
infinite loop in gemmini.h : sp_tiled_resadd()

### ISSUE THREAD

**Issue by junhyk** [ucb-bar/gemmini-rocc-tests#8]
https://github.com/ucb-bar/gemmini-rocc-tests/blob/da33d8525fed6522ea8ee9cbd9cae5e680f25672/include/gemmini.h#L1539

Hi, 

During my own project, I found that `sp_tiled_resadd()` falls into infinite loop when `J < DIM`.
It is because if `J <DIM`, then `blocks` becomes zero, which is used in the next for loop.

How should I deal with this bug?

Thanks

**Comment by hngenc** [comment]
Can you try changing that line to:

```C
const size_t blocks = J < DIM ? 1 : (J/DIM < MAX_BLOCK_LEN ? J/DIM : MAX_BLOCK_LEN);
```

And seeing if that works?

**Comment by hngenc** [comment]
We fixed this by replacing the line above with:

```
size_t blocks = (J/DIM + (J % DIM != 0));
if (blocks > MAX_BLOCK_LEN) blocks = MAX_BLOCK_LEN;
```

Feel free to re-open if you run into any more issues with `resadd`
